### ISSUE TITLE
16_backbone.pth

### ISSUE THREAD

**Issue by 2412594263** [vectornguyen76/face-recognition#1]
作者，您好，可以上传16_backbone.pth这个文件吗？，或者告诉一个这个是在insightface那里，哪一个训练模型训练来的？

**Comment by vectornguyen76** [comment]
Because It's bigger than 25MB in size. I already upload on gg drive.
Link here: https://drive.google.com/file/d/1kHBkWUKb3v4TnWw5ipjEVKy4pT5H8uGU/view?usp=sharing

**Comment by 2412594263** [comment]
> Because It's bigger than 25MB in size. I already upload on gg drive. Link here: https://drive.google.com/file/d/1kHBkWUKb3v4TnWw5ipjEVKy4pT5H8uGU/view?usp=sharing

thank you very much

**Comment by vectornguyen76** [comment]
It's here: https://pan.baidu.com/share/init?surl=CL-l4zWqsI1oDuEEYVhj-g
