### ISSUE TITLE
SCRFD not detecting on Long range of about 5 - 6 steps from camera..

### ISSUE THREAD

**Issue by webex85** [vectornguyen76/face-recognition#23]
Can you upload a model file or guide me how to use retinaface in it?

**Comment by vectornguyen76** [comment]
- Because the image is resized to 128x128 before detection, it is not good at detecting faces at a distance from the camera.
- I tested the performance of retinaface but the effectiveness was not high so I did not integrate it into the current system.
@webex85

**Comment by webex85** [comment]
I want a realtime face recognition system from ip camera do you think it supports?
If yes then what will be the requirements and procedure?

**Comment by vectornguyen76** [comment]
I just published a face recognition system at demo level. If you want to use in production, you can contact me in linkedin: https://www.linkedin.com/in/vectornguyen76/

**Comment by webex85** [comment]
@vectornguyen76 sent you a request on linkedin.
