### ISSUE TITLE
bbox error

### ISSUE THREAD

**Issue by yjLim17** [vectornguyen76/face-recognition#25]
If the bbox cannot track your face, the box will fly out of the webcam. How can I solve this?

**Comment by vectornguyen76** [comment]
I don't really understand your problem. But in my opinion, if you want better tracking, use the models here

https://github.com/ifzhang/ByteTrack?tab=readme-ov-file#mot17-test-model

**Comment by yjLim17** [comment]
There is a problem with the screen freezing. Don't you have this problem?
