### ISSUE TITLE
What kind of facial features does origin face_features.npz have?

### ISSUE THREAD

**Issue by youngjae-avikus** [vectornguyen76/face-recognition#4]

**Comment by vectornguyen76** [comment]
face_features.npz have the features that have been extracted through Insightface model. You can read more in https://github.com/deepinsight/insightface

**Comment by youngjae-avikus** [comment]
@vectornguyen76 

Oh, thank you. By the way, is it better to overwrite the existing `face_features.npz` when registering custom face feature?

**Comment by vectornguyen76** [comment]
face_features.npz stores the features of the faces and it is independent of each other. You can add or overwrite as you like.

**Comment by youngjae-avikus** [comment]
@vectornguyen76 
Thank you for the answer. Then I don't need it if I don't use the existing faces saved in the features in the recognition?

**Comment by vectornguyen76** [comment]
Yep, this is a sample I created to test recognition.

**Comment by youngjae-avikus** [comment]
@vectornguyen76 
When I tested it, the FPS speed is affected by the recognition model backbone rather than the query_embed size

**Comment by vectornguyen76** [comment]
Yes, if you want to improve FPS, converting to onx model is also a way.
