### ISSUE TITLE
Can you guide to train the data and run the project?

### ISSUE THREAD

**Issue by TruongVanPhuoc** [vectornguyen76/face-recognition#5]

**Comment by TruongVanPhuoc** [comment]
I run file train with dataset 
errorr
c:\Users\PhuocTV\Desktop\New folder\face-recognition\venv\lib\site-packages\torch\functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\TensorShape.cpp:3191.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Traceback (most recent call last):
  File "c:\Users\PhuocTV\Desktop\New folder\face-recognition\train.py", line 212, in <module>
    main(opt)
  File "c:\Users\PhuocTV\Desktop\New folder\face-recognition\train.py", line 208, in main
    training(**vars(opt))
  File "c:\Users\PhuocTV\Desktop\New folder\face-recognition\train.py", line 133, in training
    for name_person in os.listdir(source):
FileNotFoundError: [WinError 3] The system cannot find the path specified: './database/additional-training-datasets/'

**Comment by vectornguyen76** [comment]
I just updated README. Thank you!

**Comment by TruongVanPhuoc** [comment]
Thank you!
